name: example
description: "Example app for developer_tools."
publish_to: "none"
version: 0.1.0

resolution: workspace

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  developer_tools: ^0.0.1
  developer_tools_riverpod: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
