name: example
description: "Example app for developer_tools."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  developer_tools:
    path: ../
  developer_tools_riverpod:
    path: ../../developer_tools_riverpod

dependency_overrides:
  developer_tools_core:
    path: ../../developer_tools_core

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
