name: example
description: "Example app for developer_tools_riverpod."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3

  developer_tools_riverpod:
    path: ../
  developer_tools:
    path: ../../developer_tools

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.0
  riverpod_generator: ^3.0.3

dependency_overrides: 
  developer_tools_core:
    path: ../../developer_tools_core

flutter:
  uses-material-design: true
