name: developer_tools_shared_preferences
description: "Shared Preferences integration for developer_tools. Browse, search, edit, add, delete, and export stored preferences."
version: 0.0.2
topics: ["development", "debug", "tools", "shared-preferences", "flutter"]

repository: https://github.com/ramz/developer_tools
issue_tracker: https://github.com/ramz/developer_tools/issues
homepage: https://github.com/ramz/developer_tools/tree/main/packages/developer_tools_shared_preferences
license: MIT

resolution: workspace

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  developer_tools_core: ^0.0.3

  shared_preferences: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
