name: developer_tools
description: "A set of runtime tools for developers to use in their projects."
version: 0.0.6
topics: ["development", "debug", "tools", "flutter", "debug-overlay"]

repository: https://github.com/ramz/developer_tools
issue_tracker: https://github.com/ramz/developer_tools/issues
homepage: https://github.com/ramz/developer_tools/tree/main/packages/developer_tools
license: MIT

resolution: workspace

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  developer_tools_core: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
