name: developer_tools
description: "A set of runtime tools for developers to use in their projects."
version: 0.0.1
publish_to: "none"
topics: ["development", "debug", "tools", "runtime", "debug-overlay"]

resolution: workspace

environment:
  sdk: ^3.7.0
  

dependencies:
  flutter:
    sdk: flutter
  developer_tools_core: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
