name: developer_tools_riverpod
description: "Riverpod integration for developer_tools."
version: 0.0.1

resolution: workspace

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  developer_tools_core: ^0.0.1
  riverpod: ^3.2.1
  flutter_riverpod: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
