name: developer_tools_riverpod
description: "Riverpod integration for developer_tools."
version: 0.0.1

environment:
  sdk: ^3.10.7
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  developer_tools_core:
    path: ../developer_tools_core
  riverpod: ^3.2.1
  flutter_riverpod: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
