name: developer_tools_get
description: "GetX integration for developer_tools."
version: 0.0.2
topics: ["development", "debug", "tools", "getx", "flutter"]

repository: https://github.com/ramz/developer_tools
issue_tracker: https://github.com/ramz/developer_tools/issues
homepage: https://github.com/ramz/developer_tools/tree/main/packages/developer_tools_get
license: MIT

resolution: workspace

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  get: ^4.7.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
